#!/bin/bash
# pqMessenger starting script

. /lib/lsb/init-functions

if [ -r /etc/default/pqmessenger ]; then
	. /etc/default/pqmessenger
fi

PQMESSENGER_STARTUP="net.meddeb.pqmessenger.MsgDaemon"
PIDFILE="$RUN_HOME/pqmessenger.pid"
OUTFILE="$LOG_HOME/pqmessenger.out"
CONFIGFILE="$CONFIG_HOME"
#CLASSPATH="$PQMESSENGER_HOME/pqmessenger-1.0.0-SNAPSHOT.jar:$PQMESSENGER_HOME/pqmessenger"
CLASSPATH="$PQMESSENGER_HOME/*.jar"
PQMESSENGER_ARGS="--config-file $CONFIGFILE --msg-server-id $MSGSERVER_ID --connection-retry-time $CNX_RETRY_TIME"
JSVC_ARGS="-java-home $JAVA_HOME -user $PQMESSENGER_USER -pidfile $PIDFILE -outfile $OUTFILE -errfile &1 -cp $CLASSPATH"
JAVA_ARGS="-Djava.library.path=$NATIVE_LIB_HOME"
RETVAL=0

# pid function, return pqMessenger pid
pqmessengerPid() {
  PID=$( ps -ef | grep $USER | grep -v grep | grep -v root | awk '{print $2}' )
  echo $PID
}
# start function
do_start(){
  DAEMONPID=$( pqmessengerPid )
  if [ "$DAEMONPID" == "" ]; then
    echo -n "Starting pqMessenger... "
    $JSVC \
    $JSVC_ARGS \
    $JAVA_ARGS \
    $PQMESSENGER_STARTUP \
    $PQMESSENGER_ARGS
    RETVAL=$?
    if test $RETVAL -eq 0; then
      echo -e "Ok"
    else
      echo -e "Error"
    fi 
  else
    echo -e "Already started."
    RETVAL=0
  fi       
}

# stop function
do_stop(){
  echo -n "Stopping pqMessenger... "
      $JSVC \
      $JSVC_ARGS \
      -stop \
      $PQMESSENGER_STARTUP
  RETVAL=$?
  if test $RETVAL -eq 0; then
    echo "Ok."
   else
    echo "Error."
  fi    
}

# main
case "$1" in
  start)
    do_start;
    ;;
  stop)
    do_stop
    ;;
  restart)
 	  do_stop
	  sleep 1
	  do_start
	  ;;
  *)
    echo "Usage: $0 start|stop|restart" >&2
    exit 3
    ;;
esac

