#!/bin/bash
# pqMessenger starting script

USER="pqmessenger"
CONFIGFILE="/etc/ldap"
JAVA_HOME="/usr/lib/jvm/default-java"
#JAVA_HOME="/opt/java"
PPMESSENGER_HOME="/opt/pqmessenger"
LOG_HOME="/var/log/pqmessenger"
RUN_HOME="/var/run"
PPMESSENGER_STARTUP="net.meddeb.pqmessenger.MsgDaemon"
PIDFILE="$RUN_HOME/pqmessenger.pid"
OUTFILE="$LOG_HOME/pqmessenger.out"
JSVC=/usr/bin/jsvc
PPMESSENGER_ARGS="--config-file $CONFIGFILE --msg-server-id pqParams --time-retry 1800"
CLASSPATH="$PPMESSENGER_HOME/ppmessenger"
RETVAL=0

# pid function, return ppmessenger pid
ppmessengerPid() {
  PID=$( ps -ef | grep $USER | grep -v grep | grep -v root | awk '{print $2}' )
  echo $PID
}
# start function
do_start(){
  DAEMONPID=$( ppmessengerPid )
  if [ "$DAEMONPID" == "" ]; then
    echo -n "Starting ppMessenger... "
    "$JSVC" \
    -java-home "$JAVA_HOME" \
    -user "$USER" \
    -pidfile "$PIDFILE" \
    -outfile "$OUTFILE" \
    -errfile "&1" \
    -cp "$CLASSPATH" \
    "$PPMESSENGER_STARTUP" \
    $PPMESSENGER_ARGS
    RETVAL=$?
    if test $RETVAL -eq 0; then
      echo -e "Ok"
    else
      echo -e "Error"
    fi 
  else
    echo -e "Already started."
    RETVAL=0
  fi       
}

# stop function
do_stop(){
  echo -n "Stopping ppMessenger... "
      "$JSVC" \
      -java-home "$JAVA_HOME" \
      -user "$PPMESSENGER_USER" \
      -pidfile "$PIDFILE" \
      -outfile "$OUTFILE" \
      -errfile "&1" \
      -classpath "$CLASSPATH" \
      "-stop" \
      "$PPMESSENGER_STARTUP"
  RETVAL=$?
  if test $RETVAL -eq 0; then
    echo "OK."
   else
    echo "Error."
  fi    
}

# main
case "$1" in
  start)
    do_start;
    ;;
  stop)
    do_stop
    ;;
  restart)
 	  do_stop
	  sleep 1
	  do_start
	  ;;
  *)
    echo "Usage: $0 start|stop|restart" >&2
    exit 3
    ;;
esac

